### PR TITLE
GUI Overhaul and lots of fixes

### PR DESCRIPTION
**Pull request by crackedghouL**
GUI Overhaul, skip loot/pull if player is near, small state changes ..

### CODE REVIEW

**Comment by miracle091** [comment]
Some parts of the code is taken from [Better Fisher](https://github.com/miracle091/Better-Fisher), @crackedghouL have already informed me so for me is ok :smiley:

**Comment by ICEE93** [comment]
Breaks Dropdown lists like loot exclusion or mob exclusion

**Comment by crackedghouL** [comment]
Ugh, that's one of the latest commits, I quadruple-checked that, but will check again after patch.

**Comment by crackedghouL** [comment]
Also, the loot one works. It's just the mobs that don't

**Comment by crackedghouL** [comment]
I'm happy now. Anything else? Just message me on discord :)

**Comment by Triplany** [comment]
I had to wait until my security work was done. If you update this I will merge it.

**Comment by crackedghouL** [comment]
I figured ;) 
Will update on Monday or Tuesday and comment again

**Comment by crackedghouL** [comment]
will remove npc-distance-fix later, also gui not tested yet.

**Comment by crackedghouL** [comment]
This is now up to date.

**Pull request merged**
